In [5]:
import pandas as pd

df = pd.DataFrame({
    'city': ['Podgorica', 'Podgorica', 'Nikšić', 'Nikšić'],
    'weather': ['temperature', 'rain', 'temperature', 'rain'],
    'value': [25, 10, 22, 15]
})


df

        city      weather  value
0  Podgorica  temperature     25
1  Podgorica         rain     10
2     Nikšić  temperature     22
3     Nikšić         rain     15

In [ ]:
def cast(df, key, value, join_how='outer'):
    fixed_vars = df.columns.difference([key, value]) #identifies the columns that don't need to change
    '''
    df.columns.difference([key, value]) finds all column names except the ones listed in [key, value]
    '''
    
    tibble = pd.DataFrame(columns=fixed_vars) #creates an empty Dataframe(table) with the columns that didnt need to change

    #loop processes each unique weather value

    for variable_name in df[key].unique():  #this will be values from the weather column
        df_v = df[df[key] == variable_name].copy() #create a small table where all rows contain the value from the weather column
        df_v = df_v.drop(columns=[key]) #remove the column whose name is value from the weather column
        df_v = df_v.rename(columns={value: variable_name}) #rename the value column with the name from the weather column

        tibble = tibble.merge(
            df_v,
            on=list(fixed_vars),
            how=join_how
        )                           #joins each resulting table to tibble on the common column(city)

    return tibble

In [7]:
result = cast(df, 'weather', 'value')
print(result)

        city  temperature  rain
0     Nikšić           22    15
1  Podgorica           25    10

In [9]:
df = pd.DataFrame({
    'student': ['Ana', 'Ana', 'Mark', 'Mark'],
    'subject': ['Math', 'English', 'Math', 'English'],
    'score': [90, 85, 75, 80]
})
df

  student  subject  score
0     Ana     Math     90
1     Ana  English     85
2    Mark     Math     75
3    Mark  English     80

In [ ]:
def cast(df, key, value, join_how='outer'):

    keep_vars = df.columns.difference([key, value]) #finding columns to be kept

    table = pd.DataFrame(columns=keep_vars) #empty data frame with those cols

    for subject in df[key].unique():
        part_df = df[df[key] == subject].copy() #im making a copy with all the rows that contain subject in them
        part_df = part_df.drop(columns=[key]) #removing a column from that table
        part_df = part_df.rename(columns={value:subject}) #rename the column

        table = table.merge(part_df, on=list(keep_vars), how=join_how) #join the tables

    return table

In [23]:
cast(df, "subject", "score")

  student  Math  English
0     Ana    90       85
1    Mark    75       80