In [1]:
import pandas as pd

df = pd.DataFrame({
    'city': ['Podgorica', 'Podgorica', 'Nikšić', 'Nikšić'],
    'weather': ['temperature', 'rain', 'temperature', 'rain'],
    'value': [25, 10, 22, 15]
})

df

        city      weather  value
0  Podgorica  temperature     25
1  Podgorica         rain     10
2     Nikšić  temperature     22
3     Nikšić         rain     15

In [13]:
#select one weather first

temperature = df[df['weather'] == "temperature"].copy() #gives all the rows where weather is temperature

#1. remove the key column -> here it's weather because it's values will become new columns
#2. rename the value column -> here it's value because it's values will go into our new columns

temperature = temperature.drop(columns="weather") #removing the weather column

temperature = temperature.rename(columns={"value": "temperature"}) #renaming value to temperature

temperature.reset_index(drop=True)

        city  temperature
0  Podgorica           25
1     Nikšić           22

In [18]:
#repeat for other weather

rain = df[df['weather'] == 'rain'].copy() #gives all the rows where weather is rain

rain = rain.drop(columns="weather") #remove the weather column

rain = rain.rename(columns={"value": "rain"}) #rename the value column to rain

rain.reset_index(drop=True)

        city  rain
0  Podgorica    10
1     Nikšić    15

In [19]:
#merge all of the individual pieces

final_table = pd.merge(temperature, rain, on="city")

final_table

        city  temperature  rain
0  Podgorica           25    10
1     Nikšić           22    15